import "./mainStyles.css";

import styles from "./page.module.css";
export default function Page() {
  return (
    <div className={styles.main}>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
      <h1>asdasd</h1>
    </div>
  );
}
